env:
  global:
    - CC_TEST_REPORTER_ID=f832d4a72486dfcbb351b642b79f71b397851349e87551ba3ae3042e1a6d6070
    - SECRET_KEY=12345
    - DB_HOST=localhost
    - DB_USER=postgres
    - DB_NAME=banka
    - DB_PASSWORD=
    - DB_PORT=5432
language: node_js
node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
    - node_modules
script:
  - npm run test
addons:
  code_climate:
    repo_token:
      secure: "856bd52a77738b5d3e574527d4dad443b989aa57bdd3b74c167ce532ffc2a0aa"
after_success: npm run coveralls
before_script:
  - npm install
  - psql -c 'CREATE DATABASE banka;' -U postgres
  - npm run createTables
after_script:
  - coveralls < ./coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
