env:
  global:
    - CC_TEST_REPORTER_ID=856bd52a77738b5d3e574527d4dad443b989aa57bdd3b74c167ce532ffc2a0aa
language: node_js
node_js:
 - "stable"
addons:
  code_climate:
    repo_token: nDJ8gGLCWBsyee7RvO0ocazAurzQKqYKQ
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coverage
# after_success: npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT