env:
  global:
    - CC_TEST_REPORTER_ID=f832d4a72486dfcbb351b642b79f71b397851349e87551ba3ae3042e1a6d6070
language: node_js
node_js:
 - "stable"
addons:
  code_climate:
    repo_token: nDJ8gGLCWBsyee7RvO0ocazAurzQKqYKQ
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coverage
# after_success: npm run coverage
services:
  - postgresql
before_script:
  - travis_wait 30 yarn install
  - "psql -c 'create database banka;' -U postgres"
  - travis_wait npm install
  - node build/models/database.js
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT