const users = [
  {
    id: 1,
    firstName: 'Celestin',
    lastName: 'NIYONSABA',
    userName: 'niyoceles',
    password: 'celes123',
    phone: '+250783067644',
    email: 'niyoceles3@gmail.com',
    type: 'staff',
    isAdmin: true,
    location: 'Kigali',
    createdDate: '2019/04/11',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'MAFI',
    userName: 'mafi',
    password: '12345',
    phone: '+2507888888',
    email: 'mafi@gmail.com',
    type: 'client',
    isAdmin: false,
    location: 'Kigali',
    createdDate: '2019/04/12',
  },
  {
    id: 4,
    firstName: 'Alex',
    lastName: 'KALISA',
    email: 'alexk@gmail.com',
    phone: '+2507899999',
    userName: 'kalisa',
    password: 'alex123',
    isAdmin: false,
  },
];

export default users;
